<a href="https://colab.research.google.com/github/mequanent/Bioinformatics-hw2/blob/main/hw2_110761504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Clone the repository first using the following command
!npx degit https://github.com/mequanent/Bioinformatics-hw2 -f

npx: installed 1 in 1.042s
> destination directory is not empty. Using --force, continuing
> cloned mequanent/Bioinformatics-hw2#HEAD


In [ ]:
import numpy as np
np.set_printoptions(suppress=True) # Suppress displaying the scientific notation

file = open("mut.txt", "r")
lines = file.readlines()[2:] # remove the first two lines
mut = []
for line in lines:
  line = line[1:].strip().split() # remove the letters from left and the spaces
  mut.append(line)
file.close()
fi = [0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065]
mut = np.array(mut).astype(int) # convert the string array into numpy array of integers
print('mut size: ', mut.shape) # confirm if we get the right matrix size from the text
mut = np.true_divide(mut, 10000) # Change the four digit values into values between 0 & 1
print(np.round(mut, 4))

print('PAMx')
# ************* PAMx Function *********************
def pam(x):
  PAMx = mut
  for i in range(2, x+1):
    #PAMx = np.matmul(mut, PAMx)
    PAMx = np.matmul(PAMx, mut)
    #PAMx = np.rint(PAMx * 100)
    #PAMx = PAMx * 100
  return np.rint(PAMx * 100).astype(int)
# ************* End of the PAMx Function ***********
PAM250 = pam(2)
print(PAM250)

mut size:  (20, 20)
[[0.9867 0.0002 0.0009 0.001  0.0003 0.0008 0.0017 0.0021 0.0002 0.0006
  0.0004 0.0002 0.0006 0.0002 0.0022 0.0035 0.0032 0.     0.0002 0.0018]
 [0.0001 0.9913 0.0001 0.     0.0001 0.001  0.     0.     0.001  0.0003
  0.0001 0.0019 0.0004 0.0001 0.0004 0.0006 0.0001 0.0008 0.     0.0001]
 [0.0004 0.0001 0.9822 0.0036 0.     0.0004 0.0006 0.0006 0.0021 0.0003
  0.0001 0.0013 0.     0.0001 0.0002 0.002  0.0009 0.0001 0.0004 0.0001]
 [0.0006 0.     0.0042 0.9859 0.     0.0006 0.0053 0.0006 0.0004 0.0001
  0.     0.0003 0.     0.     0.0001 0.0005 0.0003 0.     0.     0.0001]
 [0.0001 0.0001 0.     0.     0.9973 0.     0.     0.     0.0001 0.0001
  0.     0.     0.     0.     0.0001 0.0005 0.0001 0.     0.0003 0.0002]
 [0.0003 0.0009 0.0004 0.0005 0.     0.9876 0.0027 0.0001 0.0023 0.0001
  0.0003 0.0006 0.0004 0.     0.0006 0.0002 0.0002 0.     0.     0.0001]
 [0.001  0.     0.0007 0.0056 0.     0.0035 0.9865 0.0004 0.0002 0.0003
  0.0001 0.0004 0.0001 0.     0.0003 0

In [ ]:
"A, R, N, D, C, Q, E, G, H, I, L, K, M, F, P, S, T, W, Y, V "
"Ala, Arg, Asn, Asp, Cys, Gln, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, Val"
"fi = 0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065"
"Mj = 100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74"
mj = [100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74]

In [ ]:
Rij = []
for i in range(20):
  Rij.append(PAM250[i] / fi[i] / 100)
Rij = np.array(Rij)

In [ ]:
m = np.array([[1., 0], [2, 3]])
res = np.log2(m, out=np.zeros_like(m), where=(m!=0))
res

array([[0.       , 0.       ],
       [1.       , 1.5849625]])

In [ ]:
S = Rij
for i in range(20):
  for j in range(20):
    if Rij[i][j] > 0:
      S[i][j] = np.rint(10 * np.log10(Rij[i][j]))
    else:
      S[i][j] = 0

for i in range(20):
  for j in range(20):
    S[i][j] = np.rint((S[i][j] + S[j][i]) / 2)
    S[j][i] = S[i][j]

print(S.astype(int))

[[ 2 -2  0  0 -2  0  0  1 -2  0 -2 -1 -2 -3  1  1  1 -3 -4  0]
 [-2  6  0 -2 -2  1 -1 -3  2 -2 -3  3 -1 -3  0  0 -1  2 -6 -2]
 [ 0  0  2  2 -4  1  2  1  2 -2 -2  1 -2 -3  0  1  1 -2 -2 -2]
 [ 0 -2  2  4 -6  2  3  1  0 -2 -4  0 -2 -6 -1  0  0 -4 -4 -2]
 [-2 -2 -4 -6 12 -6 -4 -4 -2 -2 -6 -6 -2 -4 -2  0 -2 -2  0 -2]
 [ 0  1  1  2 -6  4  3 -1  2 -3 -2  1 -2 -6  0 -1 -1 -3 -6 -2]
 [ 0 -1  2  3 -4  3  4  0  1 -2 -2  0 -2 -5  0  0  0 -4 -4 -2]
 [ 1 -3  1  1 -4 -1  0  5 -2 -3 -4 -2 -2 -4  0  1  0 -3 -5 -1]
 [-2  2  2  0 -2  2  1 -2  6 -2 -2  0 -2 -2  0 -1 -2 -1  0 -2]
 [ 0 -2 -2 -2 -2 -3 -2 -3 -2  4  2 -2  2  1 -2 -1  0 -3 -2  4]
 [-2 -3 -2 -4 -6 -2 -2 -4 -2  2  6 -2  4  2 -2 -2 -2 -1  0  2]
 [-1  3  1  0 -6  1  0 -2  0 -2 -2  5  0 -5 -1  0  0 -2 -4 -2]
 [-2 -1 -2 -2 -2 -2 -2 -2 -2  2  4  0  6 -1 -2 -2 -2 -1 -2  2]
 [-3 -3 -3 -6 -4 -6 -5 -4 -2  1  2 -5 -1  9 -5 -4 -3  0  7 -1]
 [ 1  0  0 -1 -2  0  0  0  0 -2 -2 -1 -2 -5  6  1  1 -4 -4 -1]
 [ 1  0  1  0  0 -1  0  1 -1 -1 -2  0 -2 -4  1  2  2 -1

In [ ]:
# hw1_110761504.py
# Mequanent Argaw Muluneh
# python D:\Academics\PhD\TIGP\Class\Bioinformatics\Assignments\hw1-mequanent-master\hw1_110761504.py >D:\Academics\PhD\TIGP\Class\Bioinformatics\Assignments\hw1-mequanent-master\output.txt

import os
import sys

##fn = sys.argv[1]
##if os.path.exists(fn):
##    print(os.path.basename(fn))

import numpy as np
np.set_printoptions(suppress=True) # Suppress displaying the scientific notation

path = "D:\Academics\PhD\TIGP\Class\Bioinformatics\Assignments\hw1-mequanent-master\mut.txt"
file = open(path, "r")
lines = file.readlines()[2:] # remove the first two lines
file.close()

mut = []
for line in lines:
  line = line[1:].strip().split() # remove the letters from left and the white spaces
  mut.append(line)

fi = [0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065]
mut = np.array(mut).astype(int) # convert the string array into numpy array of integers
print('\nChecking input mut size: ', mut.shape) # confirm if we get the right matrix size from the text
PAM1 = np.true_divide(mut, 10000) # Change the four digit values into values between 0 & 1

def display(values):
  print("********************************************")
  print("********************************************")
  print(values)

print("\n****************** PAM1 ********************")
display(PAM1)

# ************* PAMx Function *********************
def pam(x):
  PAM_str = "PAM" + str(x) # To make x in the PAMx flexible when displaying
  if x < 1:
    return "Please enter a number >= 1"
  elif x == 1:
    return PAM1
  else:
    PAMx = PAM1
    for i in range(2, x+1):
      PAMx = np.matmul(PAMx, PAM1) # np.matmul(mut, PAMx) also works the same
    return PAMx, PAM_str
# ************* End of the PAMx Function ***********

PAM250, PAM_str = pam(250)


print("\n********************************************")
print("****************** {} ******************".format(PAM_str))
print("********************************************\n")
# Better to display the PAM values rounded to the nearest integer
print(np.rint(PAM250 * 100).astype(int))

def log_odds():
  S = []
  for i in range(20):
    S.append(PAM250[i] / fi[i])
  S = np.array(S)

  for i in range(20):
    for j in range(20):
      if S[i][j] > 0:
        S[i][j] = 10 * np.log10(S[i][j])
      else:
        S[i][j] = 0

  # The log odds matrix should be made symmetric
  for i in range(20):
    for j in range(20):
      S[i][j] = (S[i][j] + S[j][i]) / 2
      S[j][i] = S[i][j]

  return np.rint(S).astype(int)

print("\n********************************************")
print("****** Log odds matrix for {} ***********".format(PAM_str))
print("********************************************")
print(log_odds())

