<a href="https://colab.research.google.com/github/mequanent/Bioinformatics-hws/blob/main/log_odds_of_PAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Clone the repository first using the following command
!npx degit https://github.com/mequanent/Bioinformatics-Project -f

npx: installed 1 in 2.601s
> destination directory is not empty. Using --force, continuing
> cloned mequanent/Bioinformatics-Project#HEAD


In [15]:
import numpy as np
np.set_printoptions(suppress=True) # Suppress displaying the scientific notation

file = open("mut.txt", "r")
lines = file.readlines()[2:] # remove the first two lines
mut = []
for line in lines:
  line = line[1:].strip().split() # remove the letters from left and the spaces
  mut.append(line)
file.close()
fi = [0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065]
mut = np.array(mut).astype(int) # convert the string array into numpy array of integers
print('mut size: ', mut.shape) # confirm if we get the right matrix size from the text
mut = np.true_divide(mut, 10000) # Change the four digit values into values between 0 & 1
#print(np.round(mut, 4))

# ************* PAMx Function *********************
def pam(x):
  PAMx = mut
  for i in range(2, x+1):
    PAMx = np.matmul(PAMx, mut)
  return np.rint(PAMx * 100).astype(int)
# ************* End of the PAMx Function ***********
PAM250 = pam(250)
#print('PAMx')
#print(PAM250)

mut size:  (20, 20)


In [10]:
"A, R, N, D, C, Q, E, G, H, I, L, K, M, F, P, S, T, W, Y, V "
"Ala, Arg, Asn, Asp, Cys, Gln, Glu, Gly, His, Ile, Leu, Lys, Met, Phe, Pro, Ser, Thr, Trp, Tyr, Val"
"fi = 0.087, 0.041, 0.040, 0.047, 0.033, 0.038, 0.050, 0.089, 0.034, 0.037, 0.085, 0.081, 0.015, 0.040, 0.051, 0.070, 0.058, 0.010, 0.030, 0.065"
"Mj = 100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74"
mj = [100, 65, 134, 106, 20, 93, 102, 49, 66, 96, 40, 56, 94, 41, 56, 120, 97, 18, 41, 74]

In [17]:
Rij = []
for i in range(20):
  Rij.append(PAM250[i] / fi[i] / 100)
Rij = np.array(Rij)

m = np.array([[1., 0], [2, 3]])
res = np.log2(m, out=np.zeros_like(m), where=(m!=0))

S = Rij
for i in range(20):
  for j in range(20):
    if Rij[i][j] > 0:
      S[i][j] = np.rint(10 * np.log10(Rij[i][j]))
    else:
      S[i][j] = 0

for i in range(20):
  for j in range(20):
    S[i][j] = np.rint((S[i][j] + S[j][i]) / 2)
    S[j][i] = S[i][j]
print("log-odds-of-PAM250")
print(S.astype(int))

log-odds-of-PAM250
[[ 2 -2  0  0 -2  0  0  1 -2  0 -2 -1 -2 -3  1  1  1 -3 -4  0]
 [-2  6  0 -2 -2  1 -1 -3  2 -2 -3  3 -1 -3  0  0 -1  2 -6 -2]
 [ 0  0  2  2 -4  1  2  1  2 -2 -2  1 -2 -3  0  1  1 -2 -2 -2]
 [ 0 -2  2  4 -6  2  3  1  0 -2 -4  0 -2 -6 -1  0  0 -4 -4 -2]
 [-2 -2 -4 -6 12 -6 -4 -4 -2 -2 -6 -6 -2 -4 -2  0 -2 -2  0 -2]
 [ 0  1  1  2 -6  4  3 -1  2 -3 -2  1 -2 -6  0 -1 -1 -3 -6 -2]
 [ 0 -1  2  3 -4  3  4  0  1 -2 -2  0 -2 -5  0  0  0 -4 -4 -2]
 [ 1 -3  1  1 -4 -1  0  5 -2 -3 -4 -2 -2 -4  0  1  0 -3 -5 -1]
 [-2  2  2  0 -2  2  1 -2  6 -2 -2  0 -2 -2  0 -1 -2 -1  0 -2]
 [ 0 -2 -2 -2 -2 -3 -2 -3 -2  4  2 -2  2  1 -2 -1  0 -3 -2  4]
 [-2 -3 -2 -4 -6 -2 -2 -4 -2  2  6 -2  4  2 -2 -2 -2 -1  0  2]
 [-1  3  1  0 -6  1  0 -2  0 -2 -2  5  0 -5 -1  0  0 -2 -4 -2]
 [-2 -1 -2 -2 -2 -2 -2 -2 -2  2  4  0  6 -1 -2 -2 -2 -1 -2  2]
 [-3 -3 -3 -6 -4 -6 -5 -4 -2  1  2 -5 -1  9 -5 -4 -3  0  7 -1]
 [ 1  0  0 -1 -2  0  0  0  0 -2 -2 -1 -2 -5  6  1  1 -4 -4 -1]
 [ 1  0  1  0  0 -1  0  1 -1 -1 -2  